# Generated by Django 4.2.11 on 2024-03-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0004_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_emp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='total_emp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
