# Generated by Django 4.2.11 on 2024-03-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0005_company_current_emp_company_total_emp_file_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
